# Copyright 1999-2006 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.15.0

inherit perl-module

S=${WORKDIR}/DBIx-OO-0.0.9-Divy2p

DESCRIPTION="No description available"
HOMEPAGE="http://search.cpan.org/search?query=DBIx-OO&mode=dist"
SRC_URI="mirror://cpan/authors/id/M/MI/MISHOO/DBIx-OO-0.0.9.tar.gz"


IUSE=""

SLOT="0"
LICENSE="|| ( Artistic GPL-2 )"
KEYWORDS="~x86"

DEPEND="dev-perl/SQL-Abstract
	dev-perl/Test-Pod-Coverage
	dev-perl/Class-Data-Inheritable
	dev-perl/DBI
	dev-lang/perl"
