# Copyright 1999-2006 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.15.0

inherit perl-module

S=${WORKDIR}/Net-IMAP-Client-0.93-8kK20v

DESCRIPTION="No description available"
HOMEPAGE="http://search.cpan.org/search?query=Net-IMAP-Client&mode=dist"
SRC_URI="mirror://cpan/authors/id/M/MI/MISHOO/Net-IMAP-Client-0.93.tar.gz"


IUSE=""

SLOT="0"
LICENSE="|| ( Artistic GPL-2 )"
KEYWORDS="~x86"

DEPEND="dev-perl/IO-Socket-SSL
	dev-lang/perl"
