#!/sbin/runscript
# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License, v2 or later
# $Header: $

depend() {
	need net
}

start() {
	ebegin "Starting accel-pppd"
	start-stop-daemon --start --quiet --exec /usr/sbin/accel-pppd -- ${ACCEL_PPPD_OPTS} -p ${PID}
	eend $?
}

stop() {
	ebegin "Stopping pptpd"
	start-stop-daemon --stop --quiet --pidfile  ${PID}
	result=$?
	eend $result
}
