# Copyright 1999-2006 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.15.0

inherit perl-module

S=${WORKDIR}/Template-Alloy-1.013-VHuwYm

DESCRIPTION="TT2/3, HT, HTE, Tmpl, and Velocity Engine"
HOMEPAGE="http://search.cpan.org/search?query=Template-Alloy&mode=dist"
SRC_URI="mirror://cpan/authors/id/R/RH/RHANDOM/Template-Alloy-1.013.tar.gz"


IUSE=""

SLOT="0"
LICENSE="|| ( Artistic GPL-2 )"
KEYWORDS="~x86"

DEPEND="dev-lang/perl"
