#!/sbin/runscript
# Copyright 1999-2011 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

depend() {
	use net
	before modules
}

start() {
	 ebegin "Starting usbip"

	start-stop-daemon   --start --quiet --pidfile /var/run/usbipd.pid \
		--exec /usr/bin/usbipd -- -D

	eend $? "Failed to start usbipd"
}

stop() {
	ebegin "Stopping usbip"

	 start-stop-daemon --stop --quiet --pidfile /var/run/usbipd.pid
	 
	 eend $? "Failed to stop usbipd"

}
