# Copyright 1999-2006 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.15.0

inherit perl-module

S=${WORKDIR}/Apache-Session-Wrapper-0.33-hc59Rw

DESCRIPTION="No description available"
HOMEPAGE="http://search.cpan.org/search?query=Apache-Session-Wrapper&mode=dist"
SRC_URI="mirror://cpan/authors/id/D/DR/DROLSKY/Apache-Session-Wrapper-0.33.tar.gz"


IUSE=""

SLOT="0"
LICENSE="|| ( Artistic GPL-2 )"
KEYWORDS="~x86"

DEPEND="dev-perl/Exception-Class
	>=dev-perl/Params-Validate-0.91
	>=dev-perl/Apache-Session-1.88
	dev-perl/Class-Container
	dev-lang/perl"
