#!/sbin/openrc-run
# Copyright 1999-2020 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

depend() {
	need localmount
	after hasplm
}

start() {
	ebegin "Starting HARDLOCK daemon"
	start-stop-daemon --start --quiet --exec /usr/sbin/aksusbd -- -l3
	eend $?
}

stop() {
	ebegin "Stopping HARDLOCK daemon"
	start-stop-daemon --stop --quiet --exec /usr/sbin/aksusbd
	eend $?
}
