#!/sbin/openrc-run
# Copyright 1999-2020 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

depend () {
	need net localmount
}

start() {
	ebegin "Starting HASP SRM"
	start-stop-daemon --start --quiet --exec /usr/sbin/hasplmd -- ${HASPLMD_ARGS}
	eend $?
}

stop() {
	ebegin "Stopping HASP SRM"
	start-stop-daemon --stop --quiet --retry 10 --exec /usr/sbin/hasplmd
	eend $?
}
