# Copyright 1999-2006 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.15.0

inherit perl-module

S=${WORKDIR}/Regexp-Common-Email-Address-1.01-kgMH7U

DESCRIPTION="No description available"
HOMEPAGE="http://search.cpan.org/search?query=Regexp-Common-Email-Address&mode=dist"
SRC_URI="mirror://cpan/authors/id/C/CW/CWEST/Regexp-Common-Email-Address-1.01.tar.gz"


IUSE=""

SLOT="0"
LICENSE="|| ( Artistic GPL-2 )"
KEYWORDS="~x86"

DEPEND=">=dev-perl/regexp-common-2.122
	dev-lang/perl"
